[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$solution = Join-Path $repoRoot 'IdeaCadConnector.sln'
if (-not (Test-Path $solution)) {
    throw "Run this package inside the IdeaCadConnector repository. Solution not found: $solution"
}

$gitIgnore = Join-Path $repoRoot '.gitignore'
if (-not (Test-Path $gitIgnore)) { New-Item -ItemType File -Path $gitIgnore | Out-Null }
$begin = '# BEGIN AI WORK KIT'
$end = '# END AI WORK KIT'
$text = Get-Content $gitIgnore -Raw
if ($text -notmatch [regex]::Escape($begin)) {
    $block = @"

$begin
# Track AI governance files even though this repository broadly ignores Markdown/.github.
!AI_START_HERE.md
!DEEPSEEK.md
!docs/
!docs/ai/
!docs/ai/**
!tasks/
!tasks/ai/
!tasks/ai/**
!scripts/
!scripts/ai/
!scripts/ai/**
!.github/
!.github/ISSUE_TEMPLATE/
!.github/ISSUE_TEMPLATE/**
!.github/pull_request_template.md

# Runtime output generated by AI helper scripts.
.ai-work/
$end
"@
    Add-Content -Path $gitIgnore -Value $block -Encoding UTF8
    Write-Host 'Added AI Work Kit rules to .gitignore.' -ForegroundColor Green
} else {
    Write-Host 'AI Work Kit .gitignore block already exists.' -ForegroundColor Yellow
}

$work = Join-Path $repoRoot '.ai-work'
New-Item -ItemType Directory -Force -Path $work | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $work 'verification') | Out-Null

Write-Host "AI Work Kit initialized at: $repoRoot" -ForegroundColor Cyan
Write-Host 'Next:' -ForegroundColor Cyan
Write-Host '  1. git status --short'
Write-Host '  2. Review the new files and .gitignore change.'
Write-Host '  3. Commit the work kit separately before starting a product ticket.'
Write-Host '  4. Read tasks\ai\FIRST_5_TICKETS.md'
